import { Prisma } from '@prisma/client';

export type actionFunction = (
	prevState: any,
	formData: FormData
) => Promise<{ message: string }>;

export type CartItem = {
	productId: string;
	image: string;
	title: string;
	price: string;
	amount: number;
	company: string;
};

export type CartState = {
	cartItems: CartItem[];
	numItemsInCart: number;
	cartTotal: number;
	shipping: number;
	tax: number;
	orderTotal: number;
};

//this type is used in the CartItemsList component.  It includes the cart item and the product that the cart item is associated with. The CartItemGetPayload type is generated by Prisma and includes all the fields in the CartItem model.  The include property is used to include the product associated with the cart item.

export type CartItemWithProduct = Prisma.CartItemGetPayload<{
	include: { product: true };
}>;